---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: monetizacao-cdr-selfsigned
  namespace: monetizacao-cdr
spec:
  secretName: monetizacao-cdr-selfsigned-cert-tls
  issuerRef:
    name: ca-claro-key-pair
    kind: ClusterIssuer
  commonName: monetizacao-cdr.hom.k8s.claro.com.br
  organization:
  - Claro Brasil
