apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  application: governanca-dados
  revision: "${GIT_COMMIT_FORMATTED}" # replaced during jenkins pipeline
  env: ${KUBERNETES_CONTEXT} # replaced during jenkins pipeline
  version: "${POM_VERSION}" # replaced during jenkins pipeline
  owner: claro
commonAnnotations:
  author: "Jefferson Farias"
  email: "jefferson.barbosa@claro.com.br"
  company: "CLARO"
resources:
- ./governanca-dados-backend-deployment.yaml
- ./governanca-dados-backend-service.yaml
- ./governanca-dados-backend-ingress.yaml
- ./governanca-dados-backend-certificate.yaml
